# Generated by Django 4.1.5 on 2023-03-15 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_customuser_courses_alter_course_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auhtor_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_course', to='course.course'),
        ),
    ]
