# Generated by Django 4.1.5 on 2023-03-15 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_customuser_author_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='author_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author_is', to='course.course'),
        ),
    ]
