# Generated by Django 4.1.5 on 2023-03-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_customuser_author_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_description', models.CharField(default='Image description', max_length=150, null=True)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LessonBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(max_length=100)),
                ('block_text', models.CharField(max_length=500)),
                ('block_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.images')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100)),
                ('lesson_description', models.CharField(max_length=500)),
                ('lesson_blocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonblock')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
