# Generated by Django 4.1.5 on 2023-03-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_images_remove_course_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_lessons', to='course.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_blocks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_blocks', to='course.lessonblock'),
        ),
    ]
