# Generated by Django 4.1.5 on 2023-03-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_course_lessons_alter_lesson_lesson_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_blocks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_blocks', to='course.lessonblock'),
        ),
    ]
