# Generated by Django 4.1.5 on 2023-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_remove_course_lessons_lesson_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_blocks',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_blocks',
            field=models.ManyToManyField(blank=True, null=True, related_name='lesson_blocks', to='course.lessonblock'),
        ),
    ]
