# Generated by Django 4.1.5 on 2023-03-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_remove_lesson_lesson_blocks_lesson_lesson_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_blocks',
            field=models.ManyToManyField(blank=True, related_name='lesson_blocks', to='course.lessonblock'),
        ),
    ]
