# Generated by Django 4.1.5 on 2023-04-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0024_alter_lesson_lesson_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_blocks',
            field=models.ManyToManyField(blank=True, choices=[(1, 'Block TItle'), (2, 'Second block')], related_name='lesson_blocks', to='course.lessonblock'),
        ),
    ]
