# Generated by Django 4.1.5 on 2023-04-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_discount'),
        ('course', '0025_alter_lesson_lesson_blocks'),
    ]

    operations = [
    ]
