# Generated by Django 4.1.5 on 2023-04-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_alter_profile_created_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_courses',
            field=models.ManyToManyField(related_name='my_created', to='course.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='taken_courses',
            field=models.ManyToManyField(related_name='taken_by_me', to='course.course'),
        ),
    ]
