# Generated by Django 4.1.7 on 2023-05-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0033_alter_profile_created_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
